### ISSUE TITLE
Duplicates not handled correctly for default "move" action

### ISSUE THREAD

**Issue by electroducer** [andrewning/sortphotos#64] opened 2015-11-06 12:50 UTC
In your readme file, you say that files are checked if they are identical and if so the move / copy operation is skipped, unless the `keep-duplicates` tag is used.

Right now, files are overwritten _even though_ they are found to be duplicates, provided that `copy-files` is set to the default FALSE. This turns into a real time waster as identical files are overwritten for no reason.

Looking at the code, it seems like you may have got your variables mixed up (testing `copy-files` instead of `keep-duplicates`?). At any rate, I can't follow the logic as to why you would intentionally program it like that.

**Comment by andrewning** [comment] 2015-11-07 22:37
The rationale was that a move doesn't take any longer than a remove.  All that a move operation does is a rename.  If I didn't move then I would need to delete the remaining copy.  I chose not to do that just because it saved another set of if/else statements with the same functionally equivalent result.

Of course, the assumption of a move taking the same time as a remove is not true if you are moving across filesystems (e.g., an external drive).  In that case what you are actually doing is a copy operation anyway and not a move.  So yes, if you don't select copy but try moving between file systems, and have many duplicates, then it will will waste time.

To be honest, I never really wrote this to be a general tool and there are many use cases I didn't plan for.  I just wrote it for myself and some family members, but usage has picked up much more than I expected.  It would be a quick fix to delete the file instead of "move" if all is identical.  Make the change and submit a pull request and I will merge it.

**Comment by electroducer** [comment] 2015-11-08 12:01
Okay, I understand your rationale. I was using it to upload photos to a remote drive on a server, so like you say, it tends to waste time in that case. I'll take a look at it this week and maybe send you a pull request.

**Comment by MrAmmar** [comment] 2016-12-02 18:44
Hello, thank you for the great scripts, it is useful to me at this time, was this issue solved? Because I tried to move some files from a folder to my sorted one, and in many cases I already moved these files from another folder. The problem is, I end up with too many duplicates that cost me more space in my hard drive, so I just removed them manually.

**Comment by andrewning** [comment] 2016-12-03 00:24
Yes, but I still need to pull and run the tests.  I haven't had time to work on this, but I do need this functionality as well so I will try to push some update during the holiday break.

**Comment by andrewning** [comment] 2016-12-29 20:31
fixed with 9b1400b

**Closed by andrewning** 2016-12-29 20:31 UTC
